name: Deploy Application to heroku

on:
  push:
    branches:
      - main

jobs:
  build-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - uses: actions/upload-artifact@v2
        with:
          name: AwsIpRangeChecker.jar
          path: target/AwsIpRangeChecker.jar

  deploy-heroku:
    runs-on: ubuntu-latest
    needs: build-backend
    environment:
       name: production-heroku
       url: https://aws-ip-checker.herokuapp.com/
    env:
      HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: AwsIpRangeChecker.jar
          path: target
      - name: Login to heroku
        run: heroku container:login
      - name: Push docker container
        run: heroku container:push web -a aws-ip-checker
      - name: Deploy docker container
        run: heroku container:release web -a aws-ip-checker